"""last migration.

Revision ID: 6067cf8def25
Revises: 
Create Date: 2025-11-03 22:29:07.226174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6067cf8def25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rank_destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rank_destinations', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
