"""Create normalized taxi tracking models

Revision ID: 87b8b8986cc9
Revises: 
Create Date: 2025-10-13 21:32:38.674075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87b8b8986cc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('next_of_kin_name', sa.String(length=100), nullable=True),
    sa.Column('next_of_kin_relationship', sa.String(length=50), nullable=True),
    sa.Column('next_of_kin_phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('trip_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('origin_rank_id', sa.Integer(), nullable=False),
    sa.Column('destination_rank_id', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('fare', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_rank_id'], ['ranks.id'], ),
    sa.ForeignKeyConstraint(['origin_rank_id'], ['ranks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_passengers',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('trip_id', 'passenger_id')
    )
    with op.batch_alter_table('taxis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=True))
        batch_op.alter_column('rank_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['driver_id'])
        batch_op.create_foreign_key(None, 'drivers', ['driver_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('driver_name')
        batch_op.drop_column('driver_phone')

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_destination_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('trips_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'trip_destinations', ['trip_destination_id'], ['id'])
        batch_op.drop_column('actual_duration')
        batch_op.drop_column('passenger_count')
        batch_op.drop_column('dropoff_latitude')
        batch_op.drop_column('user_id')
        batch_op.drop_column('dropoff_longitude')
        batch_op.drop_column('pickup_latitude')
        batch_op.drop_column('pickup_location')
        batch_op.drop_column('fare')
        batch_op.drop_column('pickup_longitude')
        batch_op.drop_column('estimated_duration')
        batch_op.drop_column('dropoff_location')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.drop_column('role')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dropoff_location', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('estimated_duration', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pickup_longitude', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('fare', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pickup_location', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('pickup_latitude', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('dropoff_longitude', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dropoff_latitude', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('passenger_count', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('actual_duration', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('trips_ibfk_2'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('trip_destination_id')

    with op.batch_alter_table('taxis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_phone', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('driver_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('rank_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('driver_id')

    op.drop_table('trip_passengers')
    op.drop_table('trip_destinations')
    op.drop_table('passengers')
    op.drop_table('drivers')
    op.drop_table('admins')
    # ### end Alembic commands ###
